In [24]:
#Question 1
array=input()
import numpy as np
array=np.ones(8)
array


[0 0 0 0]  [1 0 0 0]


array([1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
#Question2
import numpy as np
a=np.array([[3,4,5],[2,5,8],[5,6,4]])
b=np.add.accumulate([a[0,0],a[1,1],a[2,2]])
c=b[2]
c

12

In [ ]:
#Question2
import numpy as np
arr =np.array =([[3,4,5],[2,5,8],[5,6,4]])
b=np.diag(arr)
c=sum(b)
c

In [10]:
#Question 4
import numpy as np
a=([3,4,5])
b=([7,8,9])
c=np.add(a,b)
c

array([10, 12, 14])

In [55]:
#Question5
import numpy as np
X= np.array([[8,2,2], [4,7,1], [6,3,9]])

Y = X - X.mean(axis=1)
print(Y)

[[ 4. -2. -4.]
 [ 0.  3. -5.]
 [ 2. -1.  3.]]
